---

- name: Controller  AWX
  hosts: controller-server
  become: true
  vars:
    gazella_group_security: swisstech
  roles:
    - role: gazellacom-awx-config
      gazellacom_mode: config_server                  # config_client, cofig_server
      gazellacom_project: gomax                       # client
      gazellacom_environment: integration             # integration, production
      gazella_key_home: /opt/vault/awx/secure

- name: gomax config integration 
  hosts: gazellacom
  become: true
  vars:
    gazella_group_security: swisstech
  roles:
    - role: gazellacom-awx-config
      gazellacom_mode: config_client                  # config_client, cofig_server
      gazellacom_project: gomax                       # client
      gazellacom_environment: integration             # integration, production
      gazellacom_client_base: '/opt/.awx'

