---

- name: Controller create key on server  AWX
  hosts: awx-server
  become: true
  vars:
    gazella_group_security: swisstech
  roles:
    - role: gazella-jobs-user-single
      gazella_mode: user_server                  # user_client, client_server
      gazella_project: gomax                       # client
      gazella_environment: production             # integration, production
      gazella_user_new: "{{ gazellauser_new }}"
      gazella_key_home: /opt/vault/awx/secure

- name: gomax create new user integration 
  hosts: gazella-erp-production
  become: true
  vars:
    gazella_group_security: swisstech
  roles:
    - role: gazella-jobs-user-single
      gazella_mode: user_client                  # config_client, cofig_server
      gazella_project: gomax                       # client
      gazella_app: erp                             # com, erp
      gazella_environment: production             # integration, production
      gazella_user_new: "{{ gazella_user_new }}"
