---
- name: gomax production restart
  hosts: gazella-erp-production
  vars:
    gazella_group_security: swisstech  
  roles:
    - role: gazella-jobs-restart-erp
      gazella_mode: restart                           # restart. restart-clean
      gazella_project: gomax                          # client
      gazella_environment: production                # integration, production
