---

- name: Controller  AWX
  hosts: awx-server
  become: true
  vars:
    gazella_group_security: swisstech
  roles:
    - role: gazella-awx-config
      gazella_mode: config_server                  # config_client, cofig_server
      gazella_project: gomax                       # client
      gazella_environment: integration             # integration, production
      gazella_key_home: /opt/vault/awx/secure

- name: gomax config integration 
  hosts: gazella-erp-integration
  become: true
  vars:
    gazella_group_security: swisstech
  roles:
    - role: gazella-awx-config
      gazella_mode: config_client                  # config_client, cofig_server
      gazella_project: gomax                       # client
      gazella_environment: integration             # integration, production
      gazella_client_base: '/opt/.awx'

